src/main/java/de/samply/mdr/gui/beans/AbstractWizard.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.io.Serializable;
import java.util.List;

import de.samply.mdr.gui.WizardStep;

/**
 * An abstract Wizard Helper class
 * @author paul
 *
 */
public abstract class AbstractWizard implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Returns all available steps in this wizard, used for the wizard status bar.
     * @return
     */
    public abstract List<WizardStep> getSteps();

    /**
     * Returns all available steps in this wizard, used for the wizard status bar.
     * The argument is used to determine the already completed steps.
     * @param view
     * @return
     */
    public List<WizardStep> getSteps(String view) {
        List<WizardStep> target = getSteps();

        int step = 1;
        boolean found = false;

        for(WizardStep s : target) {
            if(s.getHref().contains(view)) {
                found = true;
            }

            if(!found) {
                ++step;
            }
        }

        int index = 1;
        for(WizardStep s : target) {
            if(index < step) {
                s.setComplete(true);
                s.setActive(false);
            } else if (index == step) {
                s.setComplete(false);
                s.setActive(true);
            } else {
                s.setComplete(false);
                s.setActive(false);
            }

            s.setLast(false);

            index++;
        }

        target.get(target.size() - 1).setLast(true);

        return target;
    }

    /**
     * Returns true if the given viewId is the first step in this wizard.
     * @param viewId the current viewId (view.viewId)
     * @return true if the given view is the first step in this wizard.
     */
    public Boolean isFirstStep(String viewId) {
        return getSteps().get(0).getHref().contains(viewId);
    }

    /**
     * Returns true if the given viewId is the last step in this wizard.
     * @param viewId the current viewId (view.viewId)
     * @return true if the given view is the last step in this wizard.
     */
    public Boolean isLastStep(String viewId) {
        return getSteps().get(getSteps().size() - 1).getHref().contains(viewId);
    }

    /**
     * Returns to the previous step. If the current step can not be found in the
     * list of available steps, it returns null
     * @param viewId
     * @return
     */
    public String previousStep(String viewId) {
        int index = 0;

        List<WizardStep> steps = getSteps();

        for(WizardStep s : steps) {
            if(s.getHref().contains(viewId) && index != 0) {
                return steps.get(index - 1).getHref().get(0) + "?faces-redirect=true";
            }

            ++index;
        }

        return null;
    }

    /**
     * If this methods returns true, the release and draft buttons are shown.
     * Otherwise they are not shown.
     * @return
     */
    public Boolean getReleaseDraftButtons() {
        return true;
    }

    public abstract String getDesignation();

}

src/main/java/de/samply/mdr/gui/beans/ChangeWizard.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import de.samply.mdr.dal.dto.Definition;
import de.samply.mdr.dal.dto.ElementType;
import de.samply.mdr.dal.dto.IdentifiedElement;
import de.samply.mdr.dal.dto.Namespace;
import de.samply.mdr.dal.dto.ScopedIdentifier;
import de.samply.mdr.dao.DefinitionDAO;
import de.samply.mdr.dao.ElementDAO;
import de.samply.mdr.dao.IdentifiedDAO;
import de.samply.mdr.dao.MDRConnection;
import de.samply.mdr.dao.ScopedIdentifierDAO;
import de.samply.mdr.dao.utils.Importer;
import de.samply.mdr.gui.BeanValidators;
import de.samply.mdr.gui.ConnectionFactory;
import de.samply.mdr.gui.MDRElement;
import de.samply.mdr.gui.ValueDomainDTO;
import de.samply.mdr.gui.WizardStep;
import de.samply.mdr.gui.exceptions.ValidationException;
import de.samply.mdr.lib.Constants.DatatypeField;
import de.samply.mdr.lib.AdapterDefinition;
import de.samply.mdr.lib.AdapterPermissibleValue;
import de.samply.mdr.util.JSFUtil;
import de.samply.mdr.util.Mapper;
import de.samply.mdr.util.Message;
import de.samply.sdao.DAOException;

/**
 * This wizard allows *basic* changes only, that means:
 * <pre>
 * * definitions and designations (also the labels for permitted values)
 * * members (for groups)
 * * members that identify the same identified item (for records)
 * * slots
 * </pre>
 * @author paul
 *
 */
@SessionScoped
@ManagedBean
public class ChangeWizard extends DataElementGroupWizard {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private MDRElement element;

    private List<WizardStep> steps;

    private ValueDomainDTO valueDomain;

    @Override
    public String validateSlots() {
        return BeanValidators.validateSlots(getSlots()) ? "changeverify?faces-redirect=true" : null;
    }

    @Override
    public String validateDefinitions() {
        setStarted(true);
        if(BeanValidators.validateDefinitions(getDefinitions())) {
            switch(element.getElement().getElementType()) {
            case DATAELEMENT:
                if(valueDomain.getDatatype() == DatatypeField.LIST) {
                    return "changevalidation?faces-redirect=true";
                } else {
                    return "changeslots?faces-redirect=true";
                }

            case DATAELEMENTGROUP:
            case RECORD:
            default:
                return "changeassignment?faces-redirect=true";
            }
        } else {
            return null;
        }
    }

    @Override
    public ElementType getElementType() {
        if(element != null) {
            return element.getElement().getElementType();
        } else {
            return ElementType.DATAELEMENT;
        }
    }

    @Override
    public String finish() {
        String vDefinitions = validateDefinitions();
        String vIdentification = validateIdentification();
        String vMembers = validateMembers();

        if(vDefinitions == null || vIdentification == null || vMembers == null) {
            return null;
        }

        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            Namespace namespace = mdr.get(ElementDAO.class).getNamespace(getNamespace());

            ScopedIdentifier identifier = super.finish(element.getElement().getId(),
                    namespace.getId(), mdr);

            if(element.getElement().getElementType() == ElementType.DATAELEMENT) {
                if(valueDomain.getDatatype() == DatatypeField.LIST) {
                    List<AdapterPermissibleValue> values = valueDomain.getPermittedValues();
                    for(AdapterPermissibleValue value : values) {
                        for(AdapterDefinition definition : value.getDefinitions()) {
                            Definition def = Mapper.convert(definition);
                            def.setElementId(value.getId());
                            def.setScopedIdentifierId(identifier.getId());
                            mdr.get(DefinitionDAO.class).saveDefinition(def);
                        }
                    }
                }
            } else {
                Importer importer = new Importer();

                int index = 1;
                for(MDRElement element : getElements()) {
                    ScopedIdentifier sub = importer.importElement(mdr, element.getUrn(), identifier.getNamespace(), getUserBean().getUserId());
                    mdr.get(ScopedIdentifierDAO.class).addSubIdentifier(identifier.getId(), sub.getId(), index++);
                }
            }

            mdr.commit();

            return done(mdr);
        } catch (DAOException e) {
            e.printStackTrace();
            Message.addError("serverError");
            return null;
        } catch (ValidationException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Initializes this wizard for the given URN.
     * @param urn
     * @return
     */
    public String initialize(String urn) {
        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            element = template(urn, mdr);

            steps = new ArrayList<>();
            steps.add(new WizardStep(JSFUtil.getString("definitions"), 1, "/user/changedefinitions.xhtml"));

            if(element.getElement().getElementType() == ElementType.DATAELEMENT) {
                valueDomain = Mapper.createValueDomain(element.getElement(), mdr, getUserBean().getSelectedLanguage());

                if(valueDomain.getDatatype() == DatatypeField.LIST) {
                    steps.add(new WizardStep(JSFUtil.getString("validation"), 2, "/user/changevalidation.xhtml"));
                }
            } else if(element.getElement().getElementType() == ElementType.DATAELEMENTGROUP) {
                setElements(Mapper.convertElements(mdr.get(IdentifiedDAO.class).getSubMembers(urn),
                        getUserBean().getSelectedLanguage(), true));
                steps.add(new WizardStep(JSFUtil.getString("membersShort"), 2, "/user/changeassignment.xhtml"));
            } else {
                setElements(Mapper.convertElements(mdr.get(IdentifiedDAO.class).getEntries(urn),
                        getUserBean().getSelectedLanguage(), false));
                steps.add(new WizardStep(JSFUtil.getString("entries"), 2, "/user/changeassignment.xhtml"));
            }

            steps.add(new WizardStep(JSFUtil.getString("slots"), 3, "/user/changeslots.xhtml"));
            steps.add(new WizardStep(JSFUtil.getString("verification"), 4, "/user/changeverify.xhtml"));

        } catch (DAOException e) {
            reset();
            return null;
        }
        return "/user/changedefinitions.xhtml?faces-redirect=true";
    }

    public String validateValidation() {
        return BeanValidators.validateValidation(valueDomain) ? "changeslots?faces-redirect=true" : null;
    }

    /* (non-Javadoc)
     * @see de.samply.mdr.gui.beans.DataElementGroupWizard#elementValid(de.samply.mdr.gui.MDRElement)
     */
    @Override
    protected boolean elementValid(MDRElement foundElement) {
        /**
         * Records allows dataelements only.
         */
        if(getElementType() == ElementType.RECORD) {
            return foundElement.getElement().getElementType() == ElementType.DATAELEMENT;
        } else {
            return super.elementValid(foundElement);
        }
    }

    /**
     * If the element we are changing is a record, check its dataelements for identity
     * @return
     */
    @Override
    public String validateMembers() {
        if(getElementType() == ElementType.RECORD) {
            try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
                List<IdentifiedElement> entries = mdr.get(IdentifiedDAO.class).getEntries(element.getUrn());

                if(getElements().size() != entries.size()) {
                    Message.addError("invalidMemberCount");
                    return null;
                }

                for(int i = 0; i < entries.size(); ++i) {
                    IdentifiedElement element = mdr.get(IdentifiedDAO.class).getElement(getElements().get(i).getUrn());
                    if(element.getId() != entries.get(i).getId()) {
                        Message.addError("invalidElement", element.getScoped().toString());
                        return null;
                    }
                }
                return "changeslots?faces-redirect=true";
            } catch (DAOException e) {
                e.printStackTrace();
                return null;
            }
        } else {
            return "changeslots?faces-redirect=true";
        }
    }

    @Override
    public String reset() {

src/main/java/de/samply/mdr/gui/beans/ImportBean.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import de.samply.mdr.dao.MDRConnection;
import de.samply.mdr.dao.utils.Importer;
import de.samply.mdr.gui.ConnectionFactory;
import de.samply.mdr.gui.MDRElement;
import de.samply.mdr.gui.MDRNamespace;
import de.samply.sdao.DAOException;

/**
 * Handles the import of one element into another namespace
 * @author paul
 *
 */
@ManagedBean
@ViewScoped
public class ImportBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    @ManagedProperty("#{userBean}")
    private UserBean userBean;

    /**
     * imports the given element into the given namespace.
     * @param element
     * @param namespace
     * @return
     */
    public String importElement(MDRElement element, MDRNamespace namespace) {
        Importer importer = new Importer();

        /**
         * If the namespace is not writable, abort without an error message. The user tried to do something he
         * shouldn't be able to do anyway.
         */
        if(!userBean.isWritableNamespace(namespace)) {
            return null;
        }

        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            String redirect = "/detail.xhtml?faces-redirect=true&urn="
                    + importer.importElement(mdr, element.getUrn(),	namespace.getName(), userBean.getUserId());

            mdr.commit();
            return redirect;
        } catch (DAOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public UserBean getUserBean() {
        return userBean;
    }

    public void setUserBean(UserBean userBean) {
        this.userBean = userBean;
    }

}

src/main/webapp/user/catalogverify.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/verify.xhtml">

    <ui:param name="bean" value="#{catalogWizard}"/>

    <ui:define name="afterDefinitions">

    </ui:define>
</ui:composition>

src/main/webapp/user/changeassignment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/assignment.xhtml">

    <f:metadata>
        <f:viewAction action="#{viewBean.initialize()}"/>
    </f:metadata>

    <ui:param name="bean" value="#{changeWizard}" />
    <ui:param name="title" value="#{msg.assignMembers}"/>

</ui:composition>

src/main/webapp/user/changensdefinitions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/definitions.xhtml">

    <ui:param name="bean" value="#{changeNamespaceWizard}" />

</ui:composition>

src/main/webapp/user/changenspermissions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/wizard.xhtml">

    <ui:param name="bean" value="#{changeNamespaceWizard}"/>

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.permissions}"/>

    <ui:define name="formContainer">

        <div class="well col-xs-12">

            <sa:nspermissions bean="#{changeNamespaceWizard}" readonly="false"/>

        </div>

        <h2>#{msg.addNewPermission}</h2>

        <div class="col-xs-12 well">
            <div class="form-group">
                <div class="col-xs-6 select2Email">
                    <h:inputHidden value="#{changeNamespaceWizard.identity}" pt:style="width: 100%;" pt:class="form-control" />
                </div>

                <h:panelGroup styleClass="col-xs-4" id="definition" layout="block">
                    <h:selectOneMenu styleClass="form-control select2" value="#{changeNamespaceWizard.permission}" disabled="#{cc.attrs.readonly}">
                        <f:selectItems var="l" value="#{mdr.permissions}" itemValue="#{l}" itemLabel="#{msg[l]}"/>
                    </h:selectOneMenu>
                </h:panelGroup>

                <div class="col-xs-2">
                    <h:commandButton styleClass="btn btn-default" value="#{msg.add}" action="#{changeNamespaceWizard.add}">
                        <f:ajax render="@form" execute="@form"/>
                    </h:commandButton>
                </div>
            </div>
        </div>

        <h:commandButton id="cancelBtn" action="#{changeNamespaceWizard.reset}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="#{changeNamespaceWizard.previousStep(view.viewId)}" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{changeNamespaceWizard.validatePermissions}" style="display:none;"/>

        <h:outputScript>
            var globalQuery;

            $(".select2Email").find("input").select2({
                minimumInputLength: 3,
                query: function (query) {
                    $("#searchText").val(query.term);
                    $("#suggestionsButton").click();

                    globalQuery = query;
                }
            });
        </h:outputScript>
    </ui:define>

    <ui:define name="misc">
        <h:form prependId="false">
            <script>
                if(globalQuery != undefined) {
                    var data = {results: []};
                    if($("#suggestionsHidden").val().length &gt; 0) {
                        var emails = $("#suggestionsHidden").val().split(";|;");
                        var i;
                        var regex = /\[(.*)\]/;
                        for(i = 0; i &lt; emails.length; ++i) {
                            var array = regex.exec(emails[i]);

                            if(array.length == 2) {
                                var text = emails[i].replace(/\[.*\]/, "");
                                data.results.push({id: array[1], text: text});
                            }
                        }
                    }
                    globalQuery.callback(data);
                }
            </script>

            <h:inputHidden value="#{changeNamespaceWizard.searchText}" id="searchText" />
            <h:inputHidden value="#{changeNamespaceWizard.suggestions}" id="suggestionsHidden" />
            <h:commandButton action="#{changeNamespaceWizard.searchEmail}" value="NONE" style="display: none;" id="suggestionsButton">
                <f:ajax execute="@form" render="@form"/>
            </h:commandButton>
        </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/user/changeslots.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/slots.xhtml">

    <ui:param name="bean" value="#{changeWizard}" />

</ui:composition>

src/main/webapp/user/changevalidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/wizard.xhtml">

    <ui:param name="bean" value="#{changeWizard}"/>

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.validation}"/>

    <ui:define name="formContainer">
        <sa:valueDomain bean="#{changeWizard}" readonly="false" change="true"/>

        <h:commandButton id="cancelBtn" action="#{changeWizard.reset}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="changedefinitions?faces-redirect=true" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{changeWizard.validateValidation}" style="display:none;"/>

    </ui:define>

    <ui:define name="misc">
        <h:panelGroup id="scrollFragment" layout="block">
            <script type="text/javascript">
                $('html, body').animate({
                    scrollTop: $("#wizardForm div:last").offset().top
                }, 1000);
            </script>
        </h:panelGroup>
    </ui:define>
</ui:composition>

src/main/webapp/user/changeverify.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="../components/verify.xhtml">

    <ui:param name="bean" value="#{changeWizard}"/>

    <ui:define name="afterDefinitions">
        <ui:fragment rendered="#{changeWizard.elementType == 'DATAELEMENT'}">
            <h2>#{msg.validation}</h2>
            <sa:valueDomain bean="#{changeWizard}" readonly="true"/>
        </ui:fragment>


        <ui:fragment rendered="#{changeWizard.elementType == 'DATAELEMENTGROUP' or changeWizard.elementType == 'RECORD'}">
            <h2><h:outputText value="#{msg.members}"/></h2>
            <div class="clearfix" id="elements">
                <sa:elements list="#{changeWizard.elements}" emptyText="#{msg.noMembers}"/>
            </div>
        </ui:fragment>
    </ui:define>
</ui:composition>

src/main/webapp/user/update.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="/components/default.xhtml">


    <f:metadata>
        <f:viewParam name="urn" value="#{updateBean.urn}"/>
    </f:metadata>

    <ui:param name="bodyClass" value="container" />

    <ui:define name="body">

        <h:form prependId="false">
            <h:commandButton value="NONE" id="initializeButton" style="display: none;" action="#{updateBean.initialize()}">
                <f:ajax render="updateStats"/>
            </h:commandButton>
            <h:commandButton id="updateButton" action="#{updateBean.update}" value="#{msg.executeUpdate}" style="display: none;" />
        </h:form>

        <sa:pleaseWaitModal />

        <h:panelGroup id="updateStats" styleClass="fadein" layout="block" style="display: none;">

            <h:outputScript>
                $(function() {
                    var dialog = $("#pleaseWaitDialog");
                    if(dialog.hasClass("in")) {
                        dialog.modal("hide");
                        $("#updateStats").show();
                    } else {
                        dialog.modal("show");
                        $("#initializeButton").click();
                    }
                });
            </h:outputScript>

            <div class="clearfix">
                <h1 class="col-xs-12">
                    #{msg.update} #{updateBean.element.designation} (#{updateBean.element.urn})
                </h1>
            </div>

            <ui:fragment rendered="#{! updateBean.keys.isEmpty()}">

                <table class="table table-striped table-hover col-xs-12">
                    <thead>
                        <tr>
                            <th scope="col">#{msg.oldElements}</th>
                            <th scope="col">#{msg.newElements}</th>
                        </tr>
                    </thead>

                    <tbody>

                        <ui:repeat var="e" value="#{updateBean.keys}">
                        <tr class="#{updateBean.status(e)} tableVCenter">
                            <td>
                                 #{e.definition} <br/>
                                 #{e.urn}
                            </td>

                            <td>
                                <ui:fragment rendered="#{! updateBean.isDeleted(e)}">
                                    #{updateBean.replacements.get(e).definition} <br/>
                                    #{updateBean.replacements.get(e).urn}
                                </ui:fragment>

                                <ui:fragment rendered="#{updateBean.isDeleted(e)}">
                                    Deleted
                                </ui:fragment>
                            </td>
                        </tr>
                        </ui:repeat>
                    </tbody>
                </table>

                <p>#{msg.notUpdatedIgnored}</p>

                <div class="col-xs-12">
                    <button class="btn btn-primary pull-right" onclick="$('#updateButton').click();">#{msg.executeUpdate}</button>
                </div>

            </ui:fragment>

            <ui:fragment rendered="#{updateBean.keys.isEmpty()}">
                <h3>#{msg.noUpdate}</h3>
            </ui:fragment>

        </h:panelGroup>

    </ui:define>

</ui:composition>