src/main/java/de/samply/mdr/gui/beans/AbstractWizard.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.io.Serializable;
import java.util.List;

import de.samply.mdr.gui.WizardStep;

/**
 * An abstract Wizard Helper class
 * @author paul
 *
 */
public abstract class AbstractWizard implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Returns all available steps in this wizard, used for the wizard status bar.
     * @return
     */
    public abstract List<WizardStep> getSteps();

    /**
     * Returns all available steps in this wizard, used for the wizard status bar.
     * The argument is used to determine the already completed steps.
     * @param view
     * @return
     */
    public List<WizardStep> getSteps(String view) {
        List<WizardStep> target = getSteps();

        int step = 1;
        boolean found = false;

        for(WizardStep s : target) {
            if(s.getHref().contains(view)) {
                found = true;
            }

            if(!found) {
                ++step;
            }
        }

        int index = 1;
        for(WizardStep s : target) {
            if(index < step) {
                s.setComplete(true);
                s.setActive(false);
            } else if (index == step) {
                s.setComplete(false);
                s.setActive(true);
            } else {
                s.setComplete(false);
                s.setActive(false);
            }

            s.setLast(false);

            index++;
        }

        target.get(target.size() - 1).setLast(true);

        return target;
    }

    /**
     * Returns true if the given viewId is the first step in this wizard.
     * @param viewId the current viewId (view.viewId)
     * @return true if the given view is the first step in this wizard.
     */
    public Boolean isFirstStep(String viewId) {
        return getSteps().get(0).getHref().contains(viewId);
    }

    /**
     * Returns true if the given viewId is the last step in this wizard.
     * @param viewId the current viewId (view.viewId)
     * @return true if the given view is the last step in this wizard.
     */
    public Boolean isLastStep(String viewId) {
        return getSteps().get(getSteps().size() - 1).getHref().contains(viewId);
    }

    /**
     * Returns to the previous step. If the current step can not be found in the
     * list of available steps, it returns null
     * @param viewId
     * @return
     */
    public String previousStep(String viewId) {
        int index = 0;

        List<WizardStep> steps = getSteps();

        for(WizardStep s : steps) {
            if(s.getHref().contains(viewId) && index != 0) {
                return steps.get(index - 1).getHref().get(0) + "?faces-redirect=true";
            }

            ++index;
        }

        return null;
    }

    /**
     * If this methods returns true, the release and draft buttons are shown.
     * Otherwise they are not shown.
     * @return
     */
    public Boolean getReleaseDraftButtons() {
        return true;
    }

    public abstract String getDesignation();

}

src/main/java/de/samply/mdr/gui/beans/ChangeNamespaceWizard.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import de.samply.auth.client.InvalidKeyException;
import de.samply.auth.client.InvalidTokenException;
import de.samply.auth.rest.UserDTO;
import de.samply.mdr.dal.dto.Definition;
import de.samply.mdr.dal.dto.DescribedElement;
import de.samply.mdr.dal.dto.ElementType;
import de.samply.mdr.dal.dto.Namespace;
import de.samply.mdr.dal.dto.NamespacePermission.Permission;
import de.samply.mdr.dal.dto.User;
import de.samply.mdr.dao.MDRConnection;
import de.samply.mdr.dao.NamespaceDAO;
import de.samply.mdr.dao.UserDAO;
import de.samply.mdr.dao.Vocabulary;
import de.samply.mdr.gui.BeanValidators;
import de.samply.mdr.gui.ConnectionFactory;
import de.samply.mdr.gui.MDRConfig;
import de.samply.mdr.gui.NamespacePermissionDTO;
import de.samply.mdr.gui.WizardStep;
import de.samply.mdr.lib.AdapterDefinition;
import de.samply.mdr.lib.Constants.Language;
import de.samply.mdr.util.JSFUtil;
import de.samply.mdr.util.Mapper;
import de.samply.mdr.util.Message;
import de.samply.sdao.DAOException;
import de.samply.sdao.json.JSONResource;
import de.samply.sdao.json.Value;
import de.samply.string.util.StringUtil;
import de.samply.string.util.StringUtil.Builder;

/**
 * This wizard allows *basic* changes only, that means:
 *
 * - labels (also the labels for permitted values)
 * - permissions
 * - hidden flag
 *
 * @author paul
 *
 */
@SessionScoped
@ManagedBean
public class ChangeNamespaceWizard extends DataElementGroupWizard {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private List<WizardStep> steps;

    /**
     * The list of the current namespace permissions
     */
    private List<NamespacePermissionDTO> permissions;

    /**
     * If true, the namespace will be hidden.
     */
    private Boolean hidden;

    /**
     * The namespace which is being edited.
     */
    private Namespace ns;

    /**
     * The selected user identity.
     */
    private String identity;

    /**
     * The selected permission for the selected user.
     */
    private Permission permission;

    /**
     * A list of suggestions
     */
    private String suggestions;

    /**
     * The search text from the select2 drop down
     */
    private String searchText;

    /**
     * The list of users that have been loaded. Without this field the
     * database has to be queried every time.
     */
    private List<UserDTO> users;

    /**
     * The required languages.
     */
    private List<Language> languages;

    /**
     * The required slots.
     */
    private List<String> constraintSlots;

    /**
     * The selected language that will be added to the list of required languages.
     */
    private Language language;

    /**
     * The selected slot that will be added to the list of required slots.
     */
    private String slot;

    @Override
    public String validateSlots() {
        return null;
    }

    @Override
    public String validateDefinitions() {
        setStarted(true);

        if(BeanValidators.validateDefinitions(getDefinitions())) {
            return "changenspermissions?faces-redirect=true";
        } else {
            return null;
        }
    }

    /**
     * In case we need to validate the permissions, do it here.
     * @return
     */
    public String validatePermissions() {
        return "changensconstraints?faces-redirect=true";
    }

    /**
     * In case we need to verify the constraints, do it here.
     * @return
     */
    public String validateConstraints() {
        return "changensverify?faces-redirect=true";
    }

    @Override
    public ElementType getElementType() {
        return ElementType.DATAELEMENT;
    }

    @Override
    public String finish() {
        String vDefinitions = validateDefinitions();

        if(vDefinitions == null) {
            return null;
        }

        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            JSONResource constraints = new JSONResource();

            /**
             * The constaints are saved in the data field.
             */
            for(Language language : languages) {
                constraints.addProperty(Vocabulary.LANGUAGES, language.toString());
            }

            for(String slot : constraintSlots) {
                constraints.addProperty(Vocabulary.SLOTS, slot);
            }
            ns.getData().setProperty(Vocabulary.CONSTRAINTS, constraints);

            List<Definition> target = new ArrayList<Definition>();
            for(AdapterDefinition def : getDefinitions()) {
               target.add(Mapper.convert(def));
            }
            ns.setHidden(hidden);

            mdr.get(NamespaceDAO.class).updateNamespace(ns, target);

            mdr.updatePermissions(Mapper.convertPermissions(permissions), ns);

            mdr.commit();

            /**
             * Reload the namespaces.
             */
            getUserBean().reloadNamespaces(mdr);

            return "/view?faces-redirect=true&namespace=" + ns.getName();
        } catch (DAOException e) {
            e.printStackTrace();
            Message.addError("serverError");
            return null;
        }
    }

    /**
     * Initializes the wizard. Creates all steps and gets the current permissions
     * from the database.
     *
     * @param namespace the current namespace name
     * @return
     */
    public String initialize(String namespace) {
        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            DescribedElement desc = mdr.get(NamespaceDAO.class).getNamespace(namespace);

            ns = (Namespace) desc.getElement();

            steps = new ArrayList<>();
            steps.add(new WizardStep(JSFUtil.getString("definitions"), 1, "/user/changensdefinitions.xhtml"));
            steps.add(new WizardStep(JSFUtil.getString("permissions"), 2, "/user/changenspermissions.xhtml"));
            steps.add(new WizardStep(JSFUtil.getString("constraints"), 3, "/user/changensconstraints.xhtml"));
            steps.add(new WizardStep(JSFUtil.getString("verification"), 4, "/user/changensverify.xhtml"));

            setDefinitions(Mapper.convert(desc.getDefinitions()));

            permissions = Mapper.convert(mdr.getPermissions(ns), mdr);

            hidden = ns.getHidden();
            setIdentifier(ns.getName());

            languages = new ArrayList<>();
            constraintSlots = new ArrayList<>();

            JSONResource constraints = ns.getConstraints();

            for(Value value : constraints.getProperties(Vocabulary.LANGUAGES)) {
                languages.add(Language.valueOf(value.getValue()));
            }

            for(Value value : constraints.getProperties(Vocabulary.SLOTS)) {
                constraintSlots.add(value.getValue());
            }

        } catch (DAOException e) {
            e.printStackTrace();
            reset();
            return null;
        }
        return "/user/changensdefinitions.xhtml?faces-redirect=true";
    }

    /**
     * Adds the current permission
     * @return
     */
    public String add() {
        try(MDRConnection mdr = ConnectionFactory.get(getUserBean().getUserId())) {
            UserDTO userDTO = null;
            for(UserDTO u : users) {
                if(u.getId().equals(identity)) {
                    userDTO = u;
                }
            }

            /**
             * Something went wrong. Abort.
             */
            if(userDTO == null) {
                return null;
            }

            User user = mdr.get(UserDAO.class).getUserByIdentity(identity);

            /**
             * If the user has not been to the MDR yet, create him.
             */
            if(user == null) {
                user = mdr.get(UserDAO.class).createDefaultUser(identity, userDTO.getEmail(), userDTO.getName(),
                        userDTO.getExternalLabel(), MDRConfig.getNamespaceGrant(), MDRConfig.getCatalogsGrant(), MDRConfig.getExportImportGrant());
                mdr.commit();
            }

            /**
             * Search for duplicates.
             */
            for(NamespacePermissionDTO p : permissions) {
                if(p.getUserId() == user.getId()) {
                    return null;
                }
            }

            NamespacePermissionDTO dto = new NamespacePermissionDTO();
            dto.setEmail(user.getEmail());
            dto.setRealName(user.getRealName());
            dto.setUserId(user.getId());
            dto.setExternalLabel(user.getExternalLabel());
            dto.setPermission(permission);
            permissions.add(dto);

            identity = "";

src/main/java/de/samply/mdr/gui/beans/MDR.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.io.Serializable;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import de.samply.mdr.dal.dto.NamespacePermission.Permission;
import de.samply.mdr.lib.Constants.DatatypeField;
import de.samply.mdr.lib.Constants.DateRepresentation;
import de.samply.mdr.lib.Constants.Language;
import de.samply.mdr.lib.Constants.Source;
import de.samply.mdr.lib.Constants.TimeRepresentation;


/**
 * Application scoped bean that provides methods to get enums.
 * @author paul
 *
 */
@ApplicationScoped
@ManagedBean(name = "mdr")  // do not remove this name... otherwise it would be "mDR".
public class MDR implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Returns all available permissions
     * @return
     */
    public Permission[] getPermissions() {
        return Permission.values();
    }

    /**
     * Returns all available datatypes
     * @return
     */
    public DatatypeField[] getDatatypeFields() {
        return DatatypeField.values();
    }

    /**
     * Returns all available languages
     * @return
     */
    public Language[] getLanguages() {
        return Language.values();
    }

    /**
     * Returns all available date representation formats
     * @return
     */
    public DateRepresentation[] getDateRepresentations() {
        return DateRepresentation.values();
    }

    /**
     * Returns all available time representation formats
     * @return
     */
    public TimeRepresentation[] getTimeRepresentations() {
        return TimeRepresentation.values();
    }

    /**
     * Returns all available sources
     * @return
     */
    public Source[] getSources() {
        return Source.values();
    }

}

src/main/webapp/resources/samply/valueDomain.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:composite="http://java.sun.com/jsf/composite"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

<composite:interface>
    <composite:attribute name="bean"/>
    <composite:attribute name="readonly" default="false"/>
    <composite:attribute name="change" default="false"/>
    <composite:attribute name="detailPage" default="/shortDetail.xhtml"/>
</composite:interface>

<composite:implementation>
    <div class="well">

        <div class="form-group">
            <h:outputLabel value="#{msg.validationType}" for="datatype" styleClass="col-xs-2 control-label"/>

            <div class="col-xs-8">
                <h:selectOneMenu id="datatype" styleClass="form-control select2" value="#{cc.attrs.bean.valueDomain.datatype}"
                        disabled="#{cc.attrs.readonly or cc.attrs.change}">
                    <f:selectItems var="i" value="#{mdr.datatypeFields}" itemValue="#{i}" itemLabel="#{msg[i]}"/>
                    <f:ajax execute="@form" render="@form" event="change"/>
                </h:selectOneMenu>
            </div>
        </div>

        <!-- ################## -->
        <!-- Format for Strings -->
        <!-- ################## -->

        <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'STRING'}" layout="block">
            <div class="form-group" >
                <h:outputLabel value="#{msg.maxLength}" for="max-length" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-8 input-group" layout="block">
                    <span class="input-group-addon">
                        <h:selectBooleanCheckbox id="max-length" value="#{cc.attrs.bean.valueDomain.useMaxLength}" disabled="#{cc.attrs.readonly}">
                            <f:ajax execute="@form" render="@form" />
                        </h:selectBooleanCheckbox>
                    </span>

                    <h:inputText styleClass="form-control" value="#{cc.attrs.bean.valueDomain.maxLength}"
                            disabled="#{! cc.attrs.bean.valueDomain.useMaxLength || cc.attrs.readonly}" pt:placeholder="#{msg.maxLengthPlaceholder}">
                        <f:convertNumber/>
                    </h:inputText>
                </h:panelGroup>
            </div>

            <div class="form-group">
                <h:outputLabel value="#{msg.useRegex}" for="use-regex" styleClass="col-xs-2 control-label" />

                <h:panelGroup layout="block" styleClass="col-xs-8">
                    <div class="checkbox">
                        <label>
                            <h:selectBooleanCheckbox id="use-regex" value="#{cc.attrs.bean.valueDomain.useRegex}" disabled="#{cc.attrs.readonly}">
                                <f:ajax execute="@form" render="@form" />
                            </h:selectBooleanCheckbox>
                        </label>
                    </div>
                </h:panelGroup>
            </div>

            <h:panelGroup layout="block" styleClass="form-group" rendered="#{cc.attrs.bean.valueDomain.useRegex}">
                <h:outputLabel value="#{msg.regex}" for="format" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-8 #{cc.attrs.readonly ? 'form-control-static' : ''}" layout="block">
                    <h:outputText rendered="#{cc.attrs.readonly}" value="#{cc.attrs.bean.valueDomain.format}"/>
                    <h:inputText id="format" rendered="#{! cc.attrs.readonly}" styleClass="form-control" value="#{cc.attrs.bean.valueDomain.format}"
                            pt:placeholder="#{msg.regexPlaceholder}"/>
                </h:panelGroup>
            </h:panelGroup>

        </h:panelGroup>

        <!-- ##### -->
        <!-- Range -->
        <!-- ##### -->

        <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'INTEGER' or cc.attrs.bean.valueDomain.datatype == 'FLOAT'}">

            <ui:fragment rendered="#{! cc.attrs.readonly}">

                <h:panelGroup styleClass="form-group" layout="block">
                    <h:outputLabel for="within-range" value="#{msg.withinRange}" styleClass="col-xs-2 control-label" />

                    <h:panelGroup layout="block" styleClass="col-xs-8">
                        <div class="checkbox">
                            <label>
                                <h:selectBooleanCheckbox id="within-range" value="#{cc.attrs.bean.valueDomain.withinRange}" disabled="#{cc.attrs.readonly}">
                                    <f:ajax execute="@form" render="@form" />
                                </h:selectBooleanCheckbox>
                            </label>
                        </div>
                    </h:panelGroup>
                </h:panelGroup>

                <h:panelGroup styleClass="form-group" layout="block" rendered="#{cc.attrs.bean.valueDomain.withinRange}">
                    <h:outputLabel for="integer-range" value="#{msg.range}" styleClass="col-xs-2 control-label"/>

                    <h:panelGroup styleClass="col-xs-8 input-group" layout="block">
                        <span class="input-group-addon">
                            <h:selectBooleanCheckbox id="integer-range" value="#{cc.attrs.bean.valueDomain.useRangeFrom}" disabled="#{cc.attrs.readonly}">
                                <f:ajax execute="@form" render="@form" />
                            </h:selectBooleanCheckbox>
                        </span>

                        <h:inputText styleClass="form-control" value="#{cc.attrs.bean.valueDomain.rangeFrom}"
                                style="width: 50%;" disabled="#{(! cc.attrs.bean.valueDomain.useRangeFrom) or cc.attrs.readonly}">
                            <f:convertNumber groupingUsed="false"/>
                        </h:inputText>
                        <h:inputText styleClass="form-control" value="#{cc.attrs.bean.valueDomain.rangeTo}"
                                style="width: 50%;" disabled="#{(! cc.attrs.bean.valueDomain.useRangeTo) or cc.attrs.readonly}">
                            <f:convertNumber groupingUsed="false"/>
                        </h:inputText>

                        <span class="input-group-addon">
                            <h:selectBooleanCheckbox value="#{cc.attrs.bean.valueDomain.useRangeTo}" disabled="#{cc.attrs.readonly}">
                                <f:ajax execute="@form" render="@form" />
                            </h:selectBooleanCheckbox>
                        </span>
                    </h:panelGroup>
                </h:panelGroup>

            </ui:fragment>

            <ui:fragment rendered="#{cc.attrs.readonly and cc.attrs.bean.valueDomain.withinRange}">

                <h:panelGroup styleClass="form-group" layout="block">
                    <h:outputLabel for="num-range" value="#{msg.numRange}" styleClass="col-xs-2 control-label" />

                    <h:panelGroup layout="block" styleClass="col-xs-8 form-control-static">
                        <h:outputText value="#{cc.attrs.bean.valueDomain.numericRange}" id="num-range" />
                    </h:panelGroup>
                </h:panelGroup>

            </ui:fragment>

            <div class="form-group">
                <h:outputLabel for="unitOfMeasure" value="#{msg.unitOfMeasure}" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-8 #{cc.attrs.readonly ? 'form-control-static' : ''}" layout="block">
                    <h:outputText rendered="#{cc.attrs.readonly}" value="#{cc.attrs.bean.valueDomain.unitOfMeasure}"/>
                    <h:inputText id="unitOfMeasure" rendered="#{! cc.attrs.readonly}" styleClass="form-control" value="#{cc.attrs.bean.valueDomain.unitOfMeasure}"/>
                </h:panelGroup>
            </div>

        </h:panelGroup>

        <!-- ########### -->
        <!-- Date Format -->
        <!-- ########### -->

        <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'DATE' or cc.attrs.bean.valueDomain.datatype == 'DATETIME'}" layout="block">
            <div class="form-group">
                <h:outputLabel for="date-representation" value="#{msg.dateRepresentation}" styleClass="col-xs-2 control-label"/>

                <h:panelGroup layout="block" styleClass="col-xs-8">
                    <h:selectOneMenu id="date-representation" styleClass="form-control select2" value="#{cc.attrs.bean.valueDomain.dateRepresentation}"
                            disabled="#{cc.attrs.readonly}">
                        <f:selectItems var="i" value="#{mdr.dateRepresentations}" itemValue="#{i}" itemLabel="#{msg[i]}"/>
                        <f:ajax execute="@form" render="@form" />
                    </h:selectOneMenu>
                </h:panelGroup>
            </div>

            <h:panelGroup styleClass="form-group" layout="block"
                    rendered="#{cc.attrs.bean.valueDomain.datatype == 'DATE' and cc.attrs.bean.valueDomain.dateRepresentation != 'LOCAL_DATE'}">
                <h:outputLabel for="with-days" value="#{msg.withDays}" styleClass="col-xs-2 control-label" />

                <h:panelGroup layout="block" styleClass="col-xs-8">
                    <div class="checkbox">
                        <label>
                            <h:selectBooleanCheckbox id="with-days" value="#{cc.attrs.bean.valueDomain.withDays}"
                                    disabled="#{cc.attrs.readonly}">
                                <f:ajax execute="@form" render="@form" />
                            </h:selectBooleanCheckbox>
                        </label>
                    </div>
                </h:panelGroup>
            </h:panelGroup>
        </h:panelGroup>

        <!-- ########### -->
        <!-- Time Format -->
        <!-- ########### -->

        <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'DATETIME' or cc.attrs.bean.valueDomain.datatype == 'TIME'}" layout="block">
            <div class="form-group">
                <h:outputLabel for="time-representation" value="#{msg.timeRepresentation}" styleClass="col-xs-2 control-label"/>

                <h:panelGroup layout="block" styleClass="col-xs-8">
                    <h:selectOneMenu id="time-representation" styleClass="form-control select2" value="#{cc.attrs.bean.valueDomain.timeRepresentation}"
                            disabled="#{cc.attrs.readonly}">
                        <f:selectItems var="i" value="#{mdr.timeRepresentations}" itemValue="#{i}" itemLabel="#{msg[i]}"/>
                        <f:ajax execute="@form" render="@form" />
                    </h:selectOneMenu>
                </h:panelGroup>
            </div>

            <div class="form-group">
                <h:outputLabel for="with-seconds" value="#{msg.withSeconds}" styleClass="col-xs-2 control-label" />

                <h:panelGroup layout="block" styleClass="col-xs-8">
                    <div class="checkbox">
                        <label>
                            <h:selectBooleanCheckbox id="with-seconds" value="#{cc.attrs.bean.valueDomain.withSeconds}" disabled="#{cc.attrs.readonly}">
                                <f:ajax execute="@form" render="@form" />
                            </h:selectBooleanCheckbox>
                        </label>
                    </div>
                </h:panelGroup>
            </div>
        </h:panelGroup>

        <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'CATALOG'}" layout="block" styleClass="clearfix">
            <ui:fragment rendered="#{! cc.attrs.readonly}">
                <h3>#{msg.selectCatalog}</h3>

                <sa:elements list="#{cc.attrs.bean.availableCatalogs}" collapsible="false" detailLink="false" draggable="false" removable="false"
                    sortable="false" starrable="false" bean="#{cc.attrs.bean}" valueDomain="#{cc.attrs.bean.valueDomain}"/>

                <h:inputText styleClass="catalogURN" value="#{cc.attrs.bean.valueDomain.catalog}" style="display: none;" />

                <h:outputScript>
                    activateSelectableCatalog();
                </h:outputScript>
            </ui:fragment>

            <sa:element element="#{cc.attrs.bean.valueDomain.catalogRoot.element}" rendered="#{cc.attrs.readonly}"/>
        </h:panelGroup>
    </div>

    <!-- ################################# -->
    <!--  List of subcodes in the catalog  -->
    <!-- ################################# -->

    <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'CATALOG' and cc.attrs.readonly}" layout="block" styleClass="well clearfix">
        <sa:elements list="#{cc.attrs.bean.valueDomain.subCodes}" valueDomain="#{cc.attrs.bean.valueDomain}" checkable="true" collapsible="true"
            draggable="false" detailLink="false" removable="false" sortable="false" starrable="false" detailPage="#{cc.attrs.detailPage}"
            readonly="#{cc.attrs.readonly}"/>
    </h:panelGroup>

    <!-- ######################### -->
    <!--  List of permitted Values -->
    <!-- ######################### -->

    <h:panelGroup rendered="#{cc.attrs.bean.valueDomain.datatype == 'LIST'}" layout="block">
        <sa:permittedValues bean="#{cc.attrs.bean.valueDomain}" readonly="#{cc.attrs.readonly}" change="#{cc.attrs.change}"/>
    </h:panelGroup>
</composite:implementation>

</html>