src/main/java/de/samply/mdr/gui/beans/ImportWizard.java
/**
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */
package de.samply.mdr.gui.beans;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.servlet.http.Part;
import javax.xml.XMLConstants;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;

import org.xml.sax.SAXException;

import de.samply.mdr.dal.dto.Definition;
import de.samply.mdr.dal.dto.DescribedElement;
import de.samply.mdr.dal.dto.ElementType;
import de.samply.mdr.dao.MDRConnection;
import de.samply.mdr.dao.utils.Importer;
import de.samply.mdr.dao.utils.Importer.Import;
import de.samply.mdr.dao.utils.Importer.ImportStrategy;
import de.samply.mdr.gui.ConnectionFactory;
import de.samply.mdr.gui.MDRNamespace;
import de.samply.mdr.gui.WizardStep;
import de.samply.mdr.util.JSFUtil;
import de.samply.mdr.util.Message;
import de.samply.mdr.xsd.Catalog;
import de.samply.mdr.xsd.Element;
import de.samply.mdr.xsd.Export;
import de.samply.mdr.xsd.Namespace;
import de.samply.mdr.xsd.ObjectFactory;
import de.samply.sdao.DAOException;
import de.samply.sdao.json.JSONResource;

/**
 * This wizard is used to create **and change existing catalogs**.
 */
@ManagedBean
@SessionScoped
public class ImportWizard extends AbstractWizard {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * The steps of this wizard
     */
    private List<WizardStep> steps;

    /**
     * The uploaded file, must be a valid catalog XML file.
     */
    private transient Part file;

    /**
     * The deserialized uploaded export object
     */
    private Export export;

    /**
     * The current ImportStrategys
     */
    private List<ImportStrategy> strategy = Collections.emptyList();

    /**
     * The list of target namespaces. Those namespaces must be writable.
     */
    private List<MDRNamespace> targetNamespaces = Collections.emptyList();

    @ManagedProperty(value = "#{userBean}")
    private UserBean userBean;

    private List<Import> imports = Collections.emptyList();

    public ImportWizard() {
        steps = new ArrayList<>();
        steps.add(new WizardStep(JSFUtil.getString("upload"), 1, "/user/import.xhtml"));
        steps.add(new WizardStep(JSFUtil.getString("strategy"), 2, "/user/importstrategy.xhtml"));
        steps.add(new WizardStep(JSFUtil.getString("verification"), 3, "/user/importverify.xhtml"));
    }

    /**
     * @param urn
     * @return
     */
    public String initialize() {
        return steps.get(0).getHref().get(0);
    }

    /**
     * Saves the catalog in the database.
     * @return
     */
    public String finish() {
        return null;
    }

    /**
     * This method is called right after the upload. It checks if the uploaded catalog is valid (it ises the XSD file
     * to do that).
     * @return
     */
    public String upload() {
        try {
            JAXBContext context = JAXBContext.newInstance(ObjectFactory.class);

            InputStream commonXSD = Catalog.class.getClassLoader().getResourceAsStream("common.xsd");
            SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            Schema schema = sf.newSchema(new StreamSource(commonXSD));

            Validator validator = schema.newValidator();
            validator.validate(new StreamSource(file.getInputStream()));

            Object element = context.createUnmarshaller().unmarshal(file.getInputStream());

            if(!(element instanceof Export)) {
                Message.addError("invalidImportFile");
                return null;
            }

            export = (Export) element;

            strategy = new ArrayList<>();

            for(JAXBElement<? extends Element> jaxb : export.getElement()) {
                if(jaxb.getValue() instanceof de.samply.mdr.xsd.Namespace) {
                    de.samply.mdr.xsd.Namespace namespace = (Namespace) jaxb.getValue();
                    ImportStrategy is = new ImportStrategy();
                    is.setFrom(namespace.getName());

                    strategy.add(is);
                }
            }

            targetNamespaces = new ArrayList<>(userBean.getWritableNamespaces());

            return "/user/importstrategy.xhtml?faces-redirect=true";
        } catch (IOException | JAXBException e) {
            e.printStackTrace();
            Message.addError("invalidCatalog");
            return null;
        } catch (SAXException e) {
            e.printStackTrace();
            Message.addError("invalidCatalogError", e.getMessage());
            return null;
        }
    }

    public String verify() {
        try(MDRConnection mdr = ConnectionFactory.get(userBean.getUserId())) {
            Importer importer = new Importer();
            importer.importExport(export, strategy, mdr);
            imports  = importer.getImports();
            return "/user/importverify.xhtml";
        } catch (DAOException e) {
            e.printStackTrace();
        }

        return null;
    }

    public String commit() {
        try(MDRConnection mdr = ConnectionFactory.get(userBean.getUserId())) {
            Importer importer = new Importer();
            importer.importExport(export, strategy, mdr);
            mdr.commit();
        } catch (DAOException e) {
            e.printStackTrace();
        }

        return "/index?faces-redirect=true";
    }

    public MDRNamespace createNewTargetNamespace(String name, String label, int id) {
        DescribedElement newNamespace = new DescribedElement();

        de.samply.mdr.dal.dto.Namespace namespace = new de.samply.mdr.dal.dto.Namespace();
        namespace.setCreatedBy(0);
        namespace.setData(new JSONResource());
        namespace.setElementType(ElementType.NAMESPACE);
        namespace.setHidden(false);
        namespace.setId(0);
        namespace.setName(name);
        namespace.setUuid(UUID.randomUUID());

        List<Definition> definitions = new ArrayList<>();
        Definition def = new Definition();
        def.setDefinition(label);
        def.setDesignation(label);
        def.setLanguage("en");
        definitions.add(def);
        newNamespace.setDefinitions(definitions);
        newNamespace.setElement(namespace);
        return new MDRNamespace(newNamespace, userBean.getSelectedLanguage());
    }

    public String reset() {
        file = null;
        export = null;

        return "/index.xhtml?faces-direct=true";
    }

    /* (non-Javadoc)
     * @see de.samply.mdr.gui.beans.AbstractWizard#getReleaseDraftButtons()
     */
    @Override
    public Boolean getReleaseDraftButtons() {
        // TODO Auto-generated method stub
        return false;
    }

    @Override
    public List<WizardStep> getSteps() {
        return steps;
    }

    /**
     * @return the file
     */
    public Part getFile() {
        return file;
    }

    /**
     * @param file the file to set
     */
    public void setFile(Part file) {
        this.file = file;
    }

    /**
     * @return the userBean
     */
    public UserBean getUserBean() {
        return userBean;
    }

    /**
     * @param userBean the userBean to set
     */
    public void setUserBean(UserBean userBean) {
        this.userBean = userBean;
    }

    /* (non-Javadoc)
     * @see de.samply.mdr.gui.beans.AbstractWizard#getDesignation()
     */
    @Override
    public String getDesignation() {
        return "Upload file";
    }

    /**
     * @return the export
     */
    public Export getExport() {
        return export;
    }

    /**
     * @param export the export to set
     */
    public void setExport(Export export) {
        this.export = export;
    }

    /**
     * @return the strategy
     */
    public List<ImportStrategy> getStrategy() {
        return strategy;
    }

    /**
     * @param strategy the strategy to set
     */
    public void setStrategy(List<ImportStrategy> strategy) {
        this.strategy = strategy;
    }

    /**
     * @return the targetNamespaces
     */
    public List<MDRNamespace> getTargetNamespaces() {
        return targetNamespaces;
    }

    /**
     * @param targetNamespaces the targetNamespaces to set
     */
    public void setTargetNamespaces(List<MDRNamespace> targetNamespaces) {
        this.targetNamespaces = targetNamespaces;
    }

    /**
     * @return the imports
     */
    public List<Import> getImports() {
        return imports;
    }

    /**

src/main/webapp/components/2page-wizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="default.xhtml">

<ui:define name="body">

    <nav class="navbar navbar-inverse navbar-fixed-bottom fadein col-xs-12">
        <h:panelGroup styleClass="#{bodyClass}" id="wizard-buttons" layout="block">

            <div class="col-xs-12">
                <h:panelGroup styleClass="pull-right" layout="block">
                    <button onclick="$('#cancelBtn').trigger('click')" class="btn btn-default">#{msg.cancel}</button>

                    <h:panelGroup layout="block" rendered="#{bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default" disabled="disabled">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isLastStep(view.viewId)}">
                        <button onclick="$('#verifyBtn').trigger('click')" class="btn btn-default btn-load">#{msg.next}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{bean.isLastStep(view.viewId)}">
                        <ui:fragment rendered="#{bean.releaseDraftButtons}">
                            <button onclick="$('.status').val('draft'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAsDraft}</button>
                            <button onclick="$('.status').val('release'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAndRelease}</button>
                        </ui:fragment>
                        <ui:fragment rendered="#{! bean.releaseDraftButtons}">
                            <button onclick="$('#finishBtn').trigger('click');" class="btn btn-default btn-load">#{msg.finish}</button>
                        </ui:fragment>
                    </h:panelGroup>
                </h:panelGroup>
            </div>

        </h:panelGroup>
    </nav>

    <div id="wizard-background" class="fadein col-xs-12">
        <div id="form-background" class="#{bodyClass}"></div>
    </div>

    <div class="page-wrapper">

        <h:panelGroup styleClass="content" style="height: calc(100% - 70px); padding-bottom:60px; padding-top: 60px; padding-right: 15px; padding-left: 15px;"
                layout="block">

            <h:panelGroup style="display: inline-block" styleClass="col-xs-12" layout="block" rendered="#{showSteps != 'false'}">
                <h1 class="wiztitle"><h:outputText value="#{bean.designation} ‒ " rendered="#{bean.designation.length() > 0}" />  #{title}</h1>

                <div class="wizard">
                    <ul class="steps">
                        <ui:repeat var="s" value="#{bean.getSteps(view.viewId)}">
                            <li class="#{s.active ? 'active' : ''} #{s.complete ? 'complete' : ''}">
                                <span class="badge #{s.active ? 'badge-info' : ''} #{s.complete ? 'badge-success' : ''}">#{s.number}</span>
                                    #{s.title}
                                <h:panelGroup styleClass="chevron" rendered="#{! s.last}"/>
                            </li>
                        </ui:repeat>
                    </ul>
                </div>
            </h:panelGroup>

            <h:panelGroup styleClass="#{formContainerClass} scrollable" layout="block">
                <h:form id="wizardForm" styleClass="form-horizontal" prependId="false" onkeypress="return event.keyCode != 13;" enctype="multipart/form-data">
                    <ui:insert name="formContainer"/>

                    <h:outputScript>
                        enableSelect2();
                    </h:outputScript>
                </h:form>
            </h:panelGroup>

            <ui:insert name="misc"/>

        </h:panelGroup>

    </div>

</ui:define>

</ui:composition>

src/main/webapp/components/assignment.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    template="2page-wizard.xhtml">

    <ui:param name="bodyClass" value="container-fluid" />
    <ui:param name="formContainerClass" value="col-xs-6" />

    <ui:define name="formContainer">

        <h:inputHidden value="#{bean.items}" id="items"/>

        <h:commandButton style="display:none" action="#{bean.refreshItems}" id="refreshItems">
            <f:ajax render="sortableItemPanel" execute="@form"/>
        </h:commandButton>

        <h:panelGroup id="sortableItemPanel" styleClass="sortableItemPanel col-xs-12 droptrue" layout="block">

            <h:panelGroup id="dragInfo" layout="block" rendered="#{bean.elements.size() == 0}">
                <div style="font-size: 30px;">
                    <i class="fa fa-hand-o-up"></i> <br /> Add Item
                </div>
                <div>Simply drag and drop</div>
            </h:panelGroup>

            <sa:elements list="#{bean.elements}" detailLink="false" draggable="false"
                    removable="true" sortable="true" starrable="false" collapsible="false"
                    showEmptyText="false"/>

            <h:outputScript>
                activateDrag();
            </h:outputScript>

        </h:panelGroup>

        <h:commandButton id="cancelBtn" action="#{bean.reset}" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{bean.validateMembers}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="#{bean.previousStep(view.viewId)}" style="display:none;"/>

    </ui:define>

    <ui:define name="misc">
        <h:form id="starForm">
            <h:inputText id="urn" value="#{userBean.starItem}" styleClass="inputStarItemUrn" style="display: none;" />
            <h:commandButton action="#{userBean.toggle}" styleClass="inputStarItemBtn" style="display: none;" >
                <f:ajax execute="@form" render=":starredElements"/>
            </h:commandButton>
        </h:form>

        <div class="col-xs-6 scrollable panelRight">

            <ul class="nav nav-tabs" role="tablist" id="searchTabs">
                <li class="active"><a href="#viewTab" role="tab" data-toggle="tab">#{msg.view}</a></li>
                <li><a href="#searchTab" role="tab" data-toggle="tab">#{msg.search}</a></li>
                <li><a href="#searchResultTab" role="tab" data-toggle="tab">#{msg.searchResults}</a></li>
                <li><a href="#starredTab" role="tab" data-toggle="tab">#{msg.starred}</a></li>
            </ul>

            <div class="tab-content">
                <h:panelGroup id="viewTab" styleClass="tab-pane fade active in" layout="block">
                    <h:form style="display: none;" id="browseUpdateForm">
                        <h:inputText value="#{viewBean.selectedNamespace}" styleClass="hiddenBrowseSelectedNamespace" style="display: none;"/>
                        <h:commandButton action="#{viewBean.updateElements()}" styleClass="updateBrowseElementsButton" style="display: none;">
                            <f:ajax render="viewWrapper:elements" execute="@form"/>
                        </h:commandButton>
                    </h:form>

                    <sa:searchResults id="viewWrapper" bean="#{viewBean}" draggable="true" allNamespaces="false"
                        title="#{msg.browse}" emptyText="#{msg.selectNamespace}" editableNamespace="false"
                        namespaceInput=".hiddenBrowseSelectedNamespace"
                        namespaceButton=".updateBrowseElementsButton"/>
                </h:panelGroup>

                <h:panelGroup id="searchTab" styleClass="tab-pane fade" layout="block">
                    <h:form styleClass="form-horizontal">
                        <ui:include src="searchForm.xhtml">
                            <ui:param name="resultTab" value="true" />
                        </ui:include>
                    </h:form>
                </h:panelGroup>

                <h:panelGroup id="searchResultTab" styleClass="tab-pane fade" layout="block">
                    <sa:searchResults id="searchWrapper" bean="#{searchBean}" allNamespaces="true" draggable="true" emptyText="#{msg.noSearchResults}"
                        title="#{msg.searchResults}"/>
                </h:panelGroup>

                <h:panelGroup id="starredTab" styleClass="tab-pane fade" layout="block">
                    <h:panelGroup id="starredElements" layout="block">
                        <div id="elements">
                            <sa:elements list="#{userBean.starred}" draggable="true" starrable="true" collapsible="true"
                                emptyText="#{msg.noStarredItems}"/>
                        </div>

                        <h:outputScript>
                            activateDrag();
                        </h:outputScript>
                    </h:panelGroup>
                </h:panelGroup>
            </div>
        </div>
    </ui:define>

</ui:composition>

src/main/webapp/components/default.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:sa="http://java.sun.com/jsf/composite/samply">

<h:head>
    <title><ui:insert name="title">#{requestBean.title} MDR</ui:insert></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <ui:include src="styles.xhtml"/>

    <h:outputScript>
        var contextPath = '#{facesContext.externalContext.request.contextPath}';

        $(function() {
            enableSelect2();
        });
    </h:outputScript>

    <ui:insert name="head" />
</h:head>

<h:body styleClass="#{bodyClass}">

    <h:panelGroup styleClass="demo-ribbon-wrapper left fixed" rendered="#{! requestBean.isProduction()}">
        <div class="demo-ribbon">
            Demo
        </div>
    </h:panelGroup>

    <ui:include src="navbar.xhtml"/>

    <div class="navbar-shadow"/>

    <ui:include src="dialog.xhtml"/>

    <ui:insert name="body"/>

</h:body>
</html>

src/main/webapp/components/definitions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="wizard.xhtml">

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.definitions}"/>

    <ui:define name="formContainer">
        <ui:insert name="preDefinitions"/>

        <sa:definitions bean="#{bean}" readonly="false" id="definitions" scroll="true"/>

        <h:commandButton id="cancelBtn" action="#{bean.reset}" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{bean.validateDefinitions}" style="display:none;"/>
    </ui:define>

    <ui:define name="misc">
        <!-- This script just scrolls to the last div block of the permitted value that has been added. -->

        <h:panelGroup id="scrollFragment" layout="block">
            <script type="text/javascript">
            scrollTo("#wizardForm div:last");
            </script>
        </h:panelGroup>
    </ui:define>

</ui:composition>

src/main/webapp/components/dialog.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">

        <div class="modal fade" id="errorDialog" tabindex="-1" role="dialog" aria-labelledby="errorMessages">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="errorMessages">Validation errors</h4>
                    </div>
                    <div class="modal-body">
                        <span>#{msg.errors}</span>

                        <h:messages showSummary="true" showDetail="true" styleClass="list-group" errorClass="list-group-item list-group-item-danger"/>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>

            <h:outputScript>
            $(function() {
                if(#{facesContext.messageList.size()} > 0) {
                    $("#errorDialog").modal("show");
                }
            });
            </h:outputScript>
        </div>

</ui:composition>

src/main/webapp/components/messages.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:panelGroup layout="block" id="messages">
        <h:messages showSummary="false" showDetail="true"
            styleClass="list-group"
            errorClass="list-group-item list-group-item-danger"
            infoClass="list-group-item list-group-item-success" />
    </h:panelGroup>

</ui:composition>

src/main/webapp/components/slots.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="wizard.xhtml">

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.slots}"/>

    <ui:define name="formContainer">
        <div class="well">
            <sa:slots bean="#{bean}" readonly="false"/>
        </div>

        <h:commandButton id="cancelBtn" action="#{bean.reset}" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{bean.validateSlots}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="#{bean.previousStep(view.viewId)}" style="display: none;" />
    </ui:define>

</ui:composition>

src/main/webapp/components/wizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://java.sun.com/jsf/composite/samply"
    template="default.xhtml">

<ui:define name="body">

    <nav class="navbar navbar-inverse navbar-fixed-bottom fadein col-xs-12">
        <h:panelGroup styleClass="#{bodyClass}" id="wizard-buttons" layout="block">

            <div class="col-xs-12">
                <h:panelGroup styleClass="pull-right" layout="block">
                    <button onclick="$('#cancelBtn').trigger('click')" class="btn btn-default">#{msg.cancel}</button>

                    <h:panelGroup layout="block" rendered="#{bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default" disabled="disabled">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isLastStep(view.viewId)}">
                        <button onclick="$('#verifyBtn').trigger('click')" class="btn btn-default btn-load">#{msg.next}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{bean.isLastStep(view.viewId)}">
                        <ui:fragment rendered="#{bean.releaseDraftButtons}">
                            <button onclick="$('.status').val('draft'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAsDraft}</button>
                            <button onclick="$('.status').val('release'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAndRelease}</button>
                        </ui:fragment>
                        <ui:fragment rendered="#{! bean.releaseDraftButtons}">
                            <button onclick="$('#finishBtn').trigger('click');" class="btn btn-default btn-load">#{msg.finish}</button>
                        </ui:fragment>
                    </h:panelGroup>
                </h:panelGroup>
            </div>

        </h:panelGroup>
    </nav>

    <div id="wizard-background" class="fadein col-xs-12">
        <div id="form-background" class="#{bodyClass}"></div>
    </div>

    <h:panelGroup styleClass="#{facesContext.messageList.size() > 0 ? '' : 'fadein'} content" layout="block">

        <h:panelGroup style="display: inline-block" styleClass="col-xs-12" layout="block" rendered="#{showSteps != 'false'}">
            <h1 class="wiztitle"><h:outputText value="#{bean.designation} ‒ " rendered="#{bean.designation.length() > 0}" />  #{title}</h1>

            <div class="wizard">
                <ul class="steps">
                    <ui:repeat var="s" value="#{bean.getSteps(view.viewId)}">
                        <li class="#{s.active ? 'active' : ''} #{s.complete ? 'complete' : ''}">
                            <span class="badge #{s.active ? 'badge-info' : ''} #{s.complete ? 'badge-success' : ''}">#{s.number}</span>
                                #{s.title}
                            <h:panelGroup styleClass="chevron" rendered="#{! s.last}"/>
                        </li>
                    </ui:repeat>
                </ul>
            </div>
        </h:panelGroup>

        <h:panelGroup styleClass="#{formContainerClass}" layout="block">
            <h:form id="wizardForm" styleClass="form-horizontal" prependId="false" onkeypress="return event.keyCode != 13;" enctype="multipart/form-data">
                <ui:insert name="formContainer"/>

                <h:outputScript>
                    enableSelect2();
                </h:outputScript>
            </h:form>
        </h:panelGroup>

        <ui:insert name="misc"/>

    </h:panelGroup>

</ui:define>

</ui:composition>